trigger: 
- main

pool: 
   vmImage: windows-latest
variables:
 AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL: "true"



jobs:
- deployment: RunLocal
  displayName: Echo all secrets
  environment: 
    name: Test
    resourceType: virtualMachine
    resourceName: ML-PF3THZQF # only deploy to the VM resource named RESOURCE-PC
  strategy:
    runOnce:
      deploy:   
          steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'Azure subscription (28242636-78ae-47a5-83bf-6579f7c547df)'
              KeyVaultName: 'Mickes'
              SecretsFilter: '*'
              RunAsPreJob: true
          - script: echo $(YOUR_SECRET_NAME)

