trigger: 
- main

pool: 
   vmImage: windows-latest
variables:
 AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL: "true"

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
    name: Test
    resourceType: virtualMachine
    resourceName: ML-PF3THZQF # only deploy to the VM resource named RESOURCE-PC
  strategy:
    runOnce:
      deploy:   
          steps:
          - script: echo "Hello world"
